[package]
name = "fast-down"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["share121 <2854631158@qq.com>"]
description = "超级快的下载器"

[dependencies]
color-eyre = "0.6.3"
content_disposition = "0.4.0"
flume = "0.11.1"
memmap2 = "0.9.5"
mockito = "1.6.1"
rayon = "1.10.0"
reqwest = { version = "0.12.12", features = [
  "gzip",
  "brotli",
  "zstd",
  "deflate",
  "http2",
  "blocking",
] }
sanitize-filename = "0.6.0"
tempfile = "3.18.0"
urlencoding = "2.1.3"
